{"name": "test_user_not_found", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <test_reqres_api_negative.Test_negative_verification object at 0x00000189F1B4AE90>\n\n    @allure.description(\"Негативная проверка GET пользователь не найден\")\n    def test_user_not_found(self):\n        print(\"Метод GET пользователь не найден\")\n        result_get = Reqres_api.get_user_not_found()\n>       Сhecking.check_status_code(result_get, 404)\n\ntests\\test_reqres_api_negative.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>, status_code = 404\n\n    @staticmethod\n    def check_status_code(response: Response, status_code):\n>       assert status_code == response.status_code\nE       AssertionError\n\nutils\\cheking.py:13: AssertionError"}, "description": "Негативная проверка GET пользователь не найден", "steps": [{"name": "GET", "status": "passed", "start": 1685391409951, "stop": 1685391410346}], "attachments": [{"name": "stdout", "source": "a5ea6423-69c1-4e05-afc1-bcaa0fb028ad-attachment.txt", "type": "text/plain"}], "start": 1685391409951, "stop": 1685391410346, "uuid": "d6f5865f-9b6d-4bfd-8350-bb51442074da", "historyId": "51280b8ee5770d6375158bd15a54a40e", "testCaseId": "8e1fec1fa796109746dfcbb38295ea5a", "fullName": "tests.test_reqres_api_negative.Test_negative_verification#test_user_not_found", "labels": [{"name": "epic", "value": "Негативная проверка "}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_reqres_api_negative"}, {"name": "subSuite", "value": "Test_negative_verification"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "1600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_reqres_api_negative"}]}